octeontx2-pf: export missing symbols
Symbols used across modules need to be exported. Otherwise following
errors pop up:

ERROR: "otx2_mbox_up_handler_cgx_link_event"
[drivers/net/ethernet/marvell/octeontx2/nic/octeontx2_nicvf.ko] undefined!
ERROR: "mbox_handler_nix_bp_enable"
[drivers/net/ethernet/marvell/octeontx2/nic/octeontx2_nicvf.ko] undefined!

Change-Id: I53a7d11f4e493245351c96dc3dfb7bb232ecd381
Signed-off-by: Tomasz Duszynski <tduszynski@marvell.com>
Reviewed-on: https://sj1git1.cavium.com/6233
Tested-by: sa_ip-sw-jenkins
Reviewed-by: Sunil Kovvuri Goutham <Sunil.Goutham@cavium.com>
[RH: Original patch taken from marvell 88F3720 board support SDK 10.0-PR2003]
Signed-off-by: Ruiqiang Hao <Ruiqiang.Hao@windriver.com>