crypto: caam - fix building job ring as module
In case job ring is built as module, the shared descriptors libraries
also have to be built as modules - otherwise the linking will fail:
[...]
ERROR: "cnstr_shdsc_rfc4106_encap" [drivers/crypto/caam/caam_jr.ko] undefined!
ERROR: "cnstr_shdsc_aead_null_decap" [drivers/crypto/caam/caam_jr.ko] undefined!
ERROR: "cnstr_shdsc_gcm_encap" [drivers/crypto/caam/caam_jr.ko] undefined!
[...]

Fixes: 0f487805d34d ("crypto: caam - fix duplicate files linking")
Signed-off-by: Horia Geantă <horia.geanta@nxp.com>
[Xulin: Original patch taken from NXP LSDK-19.06.]
Signed-off-by: Xulin Sun <xulin.sun@windriver.com>