clk: Fix compilation errors of silicon labs si5324 driver on zynq platform
commit 93b129e46baf97dac3fe0cc4d19d68074bb26cf3 from
https://github.com/Xilinx/linux-xlnx.git

This patch fixes the following linker errors on zynq(32-bit cpu) platform
by replacing the div and mod operations with math lib api.

drivers/clk/si5324drv.o: In function `si5324_rate_approx':
si5324drv.c:(.text+0xa8): undefined reference to `__aeabi_uldivmod'
si5324drv.c:(.text+0xdc): undefined reference to `__aeabi_uldivmod'
si5324drv.c:(.text+0x13c): undefined reference to `__aeabi_uldivmod'

Signed-off-by: Venkateshwar Rao Gannavarapu <venkateshwar.rao.gannavarapu@xilinx.com>
Reviewed-by: Sandip Kothari <sandipk@xilinx.com>
Signed-off-by: Michal Simek <michal.simek@xilinx.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>