crypto: testmgr - add missing part of async completion
Based on the previous commit 7f3971368
(crypto: testmgr - move to generic async completion).

Testmgr is starting async. crypto ops and waiting for them to complete.
Move it over to generic code doing the same.

In order to fix error:
crypto/testmgr.c:1048:7: error: 'tcrypt_complete' undeclared (first use in this
		function); did you mean 'crypto_template'?
|        tcrypt_complete, &result);
|        ^~~~~~~~~~~~~~~
|        crypto_template

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>