enetc: tsn: Fix module linkage issue when TSN enabled
Fixes following link error:
ERROR: "enetc_tsn_init"
[drivers/net/ethernet/freescale/enetc/fsl-enetc.ko] undefined!
scripts/Makefile.modpost:91: recipe for target '__modpost' failed
make[1]: *** [__modpost] Error 1
Makefile:1215: recipe for target 'modules' failed
make: *** [modules] Error 2

Fixes: 32c2127 ("enetc-tsn: add enetc tsn function support")

Signed-off-by: Claudiu Manoil <claudiu.manoil@nxp.com>
(cherry picked from commit 88ad0e7ea3bb3c23bdb74b9f99ce812570f1c85a)
Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>