drm: adi_axi_hdmi: fix compiling error due to the different base
drivers/gpu/drm/adi_axi_hdmi/axi_hdmi_drv.c:41:15: error: 'drm_fb_cma_create' undeclared here (not in a function); did you mean 'drm_gem_cma_create'
  .fb_create = drm_fb_cma_create,
               ^~~~~~~~~~~~~~~~~
drm_fb_cma_create has been removed in 4.18 due to unused, so replace it with
drm_gem_fb_create.

Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>