soc: renesas: rcar_ems_ctrl: Fix build error with disabling CONFIG_CPU_FREQ
commit 97a7666960ceab82f2aa39748a65a25e3831742d from
git://git.kernel.org/pub/scm/linux/kernel/git/horms/renesas-bsp.git

The build error has occurred in rcar_ems_ctrl.c as below when
CONFIG_CPU_FREQ is disabled. This patch adds "ifdef CONFIG_CPU_FREQ"
in rcar_ems_ctrl.c.

drivers/soc/renesas/rcar_ems_ctrl.c:235:2: error: implicit
declaration of function 'cpufreq_update_policy'

Note: This is local patch for R-Car Gen3 BSP, not for upstream.

Signed-off-by: Gaku Inami <gaku.inami.xw@bp.renesas.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>