Revert "usb: DWC3: fix usb cause crash issue"
This reverts commit 27f327f7e2033d1cd54853cfba3861cc64466491.

This is to avoid below USB disk issue:
usb 1-1: reset high-speed USB device number 2 using xhci-hcd
sd 2:0:0:0: [sdb] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x00 driverbyte=0x08
sd 2:0:0:0: [sdb] tag#0 Sense Key : 0x6 [current]
sd 2:0:0:0: [sdb] tag#0 ASC=0x28 ASCQ=0x0
sd 2:0:0:0: [sdb] tag#0 CDB: opcode=0x28 28 00 00 00 00 00 00 00 08 00
print_req_error: I/O error, dev sdb, sector 0
Buffer I/O error on dev sdb, logical block 0, async page read
 sdb: unable to read partition table

Signed-off-by: Yinbo Zhu <yinbo.zhu@nxp.com>
[Xulin: Original patch taken from NXP LSDK-18.12, add with
issue information.]
Signed-off-by: Xulin Sun <xulin.sun@windriver.com>
Signed-off-by: Zhantao Tang <zhantao.tang@windriver.com>