soc: renesas: rcar_ems_ctrl: Fix coding error when initializing static var to false
commit aa3f9197a7c57bba1ad81a3a5495e62b8f2e7f63 from
git://git.kernel.org/pub/scm/linux/kernel/git/horms/renesas-bsp.git

Without this patch checkpatch script will throw out below error.
        ERROR: do not initialise statics to false
This patch will fix it.

Signed-off-by: Hien Dang <hien.dang.eb@rvc.renesas.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>